export interface CarItemProps {
    id: number,
    url: string,
    manufacturer: string,
    model: string,
    generation: string,
    modification: string, 
    releaseDate: number, 
    acceleration: number,
    maxSpeed: number,
    hp: number,
    engineDisplacement: number,
    torque: number, 
    numberCilinders: number, 
    fuel: string, 
    weight: number, 
    cfc: string, 
    transmissionType: string, 
    gears: number,
    description?: string,
    interiorImageUrl?: string
    frontDiscType?: string,
    rareDiscType?: string,
    frontDiscMaterial?: string,
    rareDiscMaterial?: string,
    frontPadsMaterial?: string,
    rarePadsMaterial?: string,
}